/* Firebase custom email action handler: password reset + email verification. */
const firebaseConfig = { apiKey:'AIzaSyDaIi_A6IYFkowDq-YYcJFGK-eFxbtx0Ds', authDomain:'nura-c0a40.firebaseapp.com', projectId:'nura-c0a40', appId:'1:527486660710:web:90a2acfe973b19e08d7da7' };
firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const query = new URLSearchParams(location.search);
const mode = query.get('mode'); const code = query.get('oobCode');
const loading = document.getElementById('loading'), reset = document.getElementById('reset'), result = document.getElementById('result');
const showResult = (title, message, error) => { loading.classList.add('hidden'); reset.classList.add('hidden'); result.classList.remove('hidden'); document.getElementById('result-title').textContent=title; const el=document.getElementById('result-message'); el.textContent=message; el.className=error?'error':'success'; const url=query.get('continueUrl'); if(url && new URL(url).origin===location.origin) document.getElementById('continue').href=url; };
if (!code || !['resetPassword','verifyEmail'].includes(mode)) showResult('Invalid link','This link is missing, invalid, or expired. Request a new email from Nura.',true);
else if (mode === 'verifyEmail') auth.applyActionCode(code).then(()=>showResult('Email verified','Your Nura account is now verified.')).catch(()=>showResult('Link expired','This verification link is invalid or has expired. Request a new one from Settings.',true));
else auth.verifyPasswordResetCode(code).then(email=>{loading.classList.add('hidden');reset.classList.remove('hidden');document.getElementById('reset-email').textContent=`Resetting the password for ${email}`;document.getElementById('reset-button').onclick=()=>{const password=document.getElementById('password').value,confirm=document.getElementById('confirm').value;if(password.length<6)return showResult('Use a longer password','Passwords must be at least six characters.',true);if(password!==confirm)return showResult('Passwords do not match','Enter the same new password twice.',true);auth.confirmPasswordReset(code,password).then(()=>showResult('Password reset','Your password has been updated. You can now sign in.')).catch(()=>showResult('Could not reset password','This link may have expired. Request a new reset email.',true));};}).catch(()=>showResult('Link expired','This password-reset link is invalid or has expired. Request a new one from Nura.',true));
