/* Reliable UI translation and Nura Watch wellbeing fallback tips. */
(()=>{
  const text={
    da:{Dashboard:'Oversigt',Watch:'Ur',Settings:'Indstillinger',Files:'Filer','New Chat':'Ny chat','No files loaded':'Ingen filer indlÃ¦st','What do you want to learn today?':'Hvad vil du lÃ¦re i dag?','Ask a concept...':'SpÃ¸rg om et emne...','Focus Timer':'Fokustimer',Library:'Bibliotek',Today:'I dag',Save:'Gem',Clear:'Ryd',Close:'Luk',Start:'Start',Pause:'Pause',Reset:'Nulstil',Calendar:'Kalender',Profile:'Profil',Account:'Konto',Devices:'Enheder',Audio:'Lyd',Preferences:'PrÃ¦ferencer',Security:'Sikkerhed',Language:'Sprog',Theme:'Tema',Notifications:'Notifikationer','Sign Out':'Log ud','Sign in':'Log ind','Create account':'Opret konto','Continue as Guest':'FortsÃ¦t som gÃ¦st','Nura Watch':'Nura Ur','Daily Goals':'Dagens mÃ¥l','New Conversation':'Ny samtale','Previous conversations':'Tidligere samtaler','Clear all sources':'Ryd alle kilder'},
    de:{Dashboard:'Ãœbersicht',Watch:'Uhr',Settings:'Einstellungen',Files:'Dateien','New Chat':'Neuer Chat','No files loaded':'Keine Dateien geladen','What do you want to learn today?':'Was mÃ¶chtest du heute lernen?','Ask a concept...':'Frage nach einem Thema...','Focus Timer':'Fokus-Timer',Library:'Bibliothek',Today:'Heute',Save:'Speichern',Clear:'Leeren',Close:'SchlieÃŸen',Start:'Start',Pause:'Pause',Reset:'ZurÃ¼cksetzen',Calendar:'Kalender',Profile:'Profil',Account:'Konto',Devices:'GerÃ¤te',Audio:'Audio',Preferences:'Einstellungen',Security:'Sicherheit',Language:'Sprache',Theme:'Design',Notifications:'Benachrichtigungen','Sign Out':'Abmelden','Sign in':'Anmelden','Create account':'Konto erstellen','Continue as Guest':'Als Gast fortfahren','Nura Watch':'Nura Watch','Daily Goals':'Tagesziele','New Conversation':'Neue Unterhaltung','Previous conversations':'Vorherige Unterhaltungen','Clear all sources':'Alle Quellen lÃ¶schen'}
  };
  const originals=new WeakMap();
  window.nuraSetLanguage=(lang)=>{lang=['da','en','de'].includes(lang)?lang:'da';localStorage.setItem('nura-language',lang);document.documentElement.lang=lang;const map=text[lang]||{};const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&!n.parentElement.closest('script,style,svg,textarea,pre,code')?1:2});const ns=[];while(w.nextNode())ns.push(w.currentNode);ns.forEach(n=>{const o=originals.get(n)||n.nodeValue;originals.set(n,o);const k=o.trim();n.nodeValue=o.replace(k,lang==='en'?k:(map[k]||k));});document.querySelectorAll('[placeholder]').forEach(e=>{const o=e.dataset.nuraOriginalPlaceholder||e.placeholder;e.dataset.nuraOriginalPlaceholder=o;e.placeholder=lang==='en'?o:(map[o]||o)});};
  document.addEventListener('DOMContentLoaded',()=>window.nuraSetLanguage(localStorage.getItem('nura-language')||'da'));
  const old=window.buildNuraAlertFallback;
  window.buildNuraAlertFallback=(f,s)=>{if(typeof old==='function'){try{return old(f,s)}catch(_){}};if(s>=75)return{message:'Your body looks overloaded. Take one small reset now â€” you deserve the pause.',tips:[{icon:'â—Œ',text:'Breathe in for 4, out for 6 â€” repeat five times.'},{icon:'â—’',text:'Drink some water and relax your shoulders.'},{icon:'â—‰',text:'Look away from the screen for 20 seconds.'}]};if(s>=50)return{message:'You are carrying some tension. A short pause can make the next task feel lighter.',tips:[{icon:'â—Œ',text:'Take three slow breaths before continuing.'},{icon:'â—’',text:'Stand up and stretch your neck and hands.'},{icon:'â—‰',text:'Choose one tiny next step, not the whole task.'}]};return{message:'You are in a steady place. Keep the pace gentle and protect your focus.',tips:[{icon:'â—‰',text:'Keep water nearby and blink slowly.'},{icon:'â—Œ',text:'After this task, reward yourself with a short break.'},{icon:'â—’',text:'Keep your shoulders soft while you work.'}]};};
})();
