/* V10: Firebase-key wait, chat-native NuraQuiz and refined local UI behavior. */
(()=>{let quiz=null;const sleep=n=>new Promise(r=>setTimeout(r,n));const hist=()=>JSON.parse(localStorage.getItem('nura-quiz-results')||'[]');
const typing=on=>{let e=document.getElementById('v10-typing');if(on&&!e){e=document.createElement('div');e.id='v10-typing';e.className='v10-typing';e.innerHTML='<i></i><i></i><i></i>';document.getElementById('chat-box')?.append(e)}if(!on)e?.remove()};
async function key(){if(!window.getApiKey?.()&&window._fetchConfigKey){await window._fetchConfigKey();await sleep(120)}return window.getApiKey?.()}
function results(){let e=document.getElementById('v10-results');if(!e){e=document.createElement('div');e.id='v10-results';e.className='v10-results';e.innerHTML='<div class="v10-results-card"><button>●</button><h3>Results</h3><div></div></div>';e.querySelector('button').onclick=()=>e.classList.remove('show');document.body.append(e)}e.querySelector('.v10-results-card div').innerHTML=hist().slice().reverse().map(x=>`<div class="v10-result"><strong>${x.topic}</strong><br>${x.score}% · ${new Date(x.at).toLocaleDateString()}</div>`).join('')||'No quiz results yet.';e.classList.add('show')}
function addResultsTab(){const host=document.getElementById('nura-chathist-tab')?.parentElement;if(host&&!document.getElementById('nura-results-tab')){const b=document.createElement('button');b.id='nura-results-tab';b.textContent='RESULTS';b.onclick=results;host.prepend(b)}}
function addQuizModel(){const dd=document.getElementById('nura-model-dropdown');if(!dd||document.getElementById('nura-tab-quiz'))return false;const b=document.createElement('div');b.id='nura-tab-quiz';b.className='model-opt';b.style.cssText='padding:10px 14px;cursor:pointer';b.textContent='NuraQuiz — conversational quiz mode';b.onclick=()=>{document.getElementById('nura-model-label').textContent='NuraQuiz';dd.style.display='none';document.getElementById('chat-input').placeholder='Make me a quiz about biology and make it 10 questions';};dd.append(b);const labels={chat:'NuraChat',research:'NuraSearch',code:'Neurode'};Object.entries(labels).forEach(([m,n])=>{const e=document.getElementById('nura-tab-'+m);if(e)e.querySelector('div div')?.replaceChildren(n)});return true}
async function startQuiz(text){const count=Math.min(Number(text.match(/(\d+)\s*questions?/i)?.[1]||10),20),topic=(text.match(/(?:about|on)\s+(.+?)(?:\s+and\s+make|$)/i)?.[1]||text).trim(),k=await key();if(!k){addMsg('ai','Nura is connecting to Firebase. Please send that again in a moment.');return}typing(true);await sleep(1200);try{const r=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+k},body:JSON.stringify({model:'llama-3.3-70b-versatile',max_tokens:2200,messages:[{role:'user',content:`Return only JSON: ${count} multiple choice quiz questions about ${topic}, [{"q":"","opts":["","","",""],"ans":0}]`}]})}),d=await r.json();quiz={topic,items:JSON.parse(d.choices[0].message.content.replace(/```json|```/g,'')),i:0,ok:0};typing(false);ask()}catch{typing(false);addMsg('ai','I could not generate that quiz. Try again.')}}
function ask(){const q=quiz.items[quiz.i];addMsg('ai',`Question ${quiz.i+1}/${quiz.items.length}: ${q.q}\nA. ${q.opts[0]}\nB. ${q.opts[1]}\nC. ${q.opts[2]}\nD. ${q.opts[3]}`)}
async function answer(text){const c='ABCD'.indexOf(text.trim().charAt(0).toUpperCase());if(c<0){addMsg('ai','Please answer A, B, C, or D.');return}quiz.ok+=c===quiz.items[quiz.i].ans?1:0;quiz.i++;if(quiz.i<quiz.items.length){typing(true);await sleep(1100);typing(false);ask();return}const score=Math.round(quiz.ok/quiz.items.length*100),h=hist(),old=h.at(-1)?.score;h.push({topic:quiz.topic,score,at:new Date().toISOString()});localStorage.setItem('nura-quiz-results',JSON.stringify(h));addMsg('ai',`Quiz complete: ${score}% (${old==null?'first result':(score-old>=0?'+':'')+(score-old)+'% compared with your last quiz'}).`);quiz=null;results()}
function timer(){const presets=document.querySelector('.focus-timer-wrap div[style*="flex-wrap"]');if(presets){presets.innerHTML='<select id="ft-mode-select"><option value="50">Deep Work · 50 min</option><option value="25">Focus · 25 min</option><option value="10">Breather · 10 min</option><option value="5">Calm Down · 5 min</option><option value="custom">Custom</option></select>';presets.className='ft-custom-row';presets.querySelector('select').onchange=e=>{if(e.target.value==='custom'){document.getElementById('ft-custom-min')?.focus()}else window.applyFocusPreset?.(Number(e.target.value),e.target.selectedOptions[0].text)}}}
document.addEventListener('DOMContentLoaded',()=>{addResultsTab();timer();let n=0;const t=setInterval(()=>{if(addQuizModel()||++n>30)clearInterval(t)},120);const old=window.sendMsg;window.sendMsg=async function(){const input=document.getElementById('chat-input'),text=input?.value.trim();if(!text)return;if(quiz){input.value='';addMsg('user',text);return answer(text)}if(/\b(make|create|give)\b.*\bquiz\b/i.test(text)){input.value='';addMsg('user',text);return startQuiz(text)}const k=await key();if(!k){addMsg('ai','Nura is connecting to Firebase. Please try again in a moment.');return}typing(true);await sleep(1100);typing(false);return old?.()};document.querySelectorAll('.modal,.popup,.nw-popup,.nw-alert-overlay,.colour-popup-overlay').forEach(e=>e.addEventListener('click',x=>{if(x.target===e)e.classList.remove('open','show')}))});})();
