/* Nura V4 interaction layer: compact sidebar, language control, smooth video. */
(()=>{
  const labels={en:{focus:'Focus',stress:'Stress',calendar:'Calendar',language:'Language',settings:'Settings',profile:'Profile'},da:{focus:'Fokus',stress:'Stress',calendar:'Kalender',language:'Sprog',settings:'Indstillinger',profile:'Profil'},de:{focus:'Fokus',stress:'Stress',calendar:'Kalender',language:'Sprache',settings:'Einstellungen',profile:'Profil'}};
  const copy={
    'Welcome back':'Velkommen tilbage|Willkommen zurück','Dashboard':'Oversigt|Übersicht','Home':'Hjem|Startseite','Notes':'Noter|Notizen','Quiz':'Quiz|Quiz','Focus':'Fokus|Fokus','Stress':'Stress|Stress','Session':'Session|Sitzung','Calendar':'Kalender|Kalender','Settings':'Indstillinger|Einstellungen','Profile':'Profil|Profil','Language':'Sprog|Sprache','Custom colour':'Brugerdefineret farve|Benutzerdefinierte Farbe','Choose your accent colour':'Vælg din accentfarve|Wähle deine Akzentfarbe','Current colour':'Nuværende farve|Aktuelle Farbe','Save':'Gem|Speichern','Cancel':'Annuller|Abbrechen','Close':'Luk|Schließen','Open':'Åbn|Öffnen','Start':'Start|Starten','Pause':'Pause|Pause','Reset':'Nulstil|Zurücksetzen','Today':'I dag|Heute','Daily Goals':'Dagens mål|Tagesziele','Focus Timer':'Fokustimer|Fokus-Timer','Audio Library':'Lydbibliotek|Audiobibliothek','Search':'Søg|Suchen','Add':'Tilføj|Hinzufügen','Delete':'Slet|Löschen','Edit':'Rediger|Bearbeiten','Name':'Navn|Name','Age':'Alder|Alter','Theme':'Tema|Design','Notifications':'Notifikationer|Benachrichtigungen','Security':'Sikkerhed|Sicherheit','Account':'Konto|Konto','Sign Out':'Log ud|Abmelden','Sign In':'Log ind|Anmelden','Continue as Guest':'Fortsæt som gæst|Als Gast fortfahren','Create Account':'Opret konto|Konto erstellen','Email address':'E-mailadresse|E-Mail-Adresse','Password':'Adgangskode|Passwort','Full name':'Fulde navn|Vollständiger Name','What do you want to learn today?':'Hvad vil du lære i dag?|Was möchtest du heute lernen?','Ask a concept...':'Spørg om et emne...|Frage nach einem Thema...','New Chat':'Ny chat|Neuer Chat','Files':'Filer|Dateien','No files loaded':'Ingen filer indlæst|Keine Dateien geladen','Library':'Bibliotek|Bibliothek','Watch':'Ur|Uhr','Nura Watch':'Nura Ur|Nura Watch','Light Engine':'Lysmotor|Lichtmaschine','Deep Focus':'Dyb fokus|Tiefer Fokus','Stable Focus':'Stabilt fokus|Stabiler Fokus','Break Mode':'Pause-tilstand|Pausenmodus','Relaxation':'Afslapning|Entspannung'
  };
  function translateAll(lang){const variant=lang==='da'?0:lang==='de'?1:-1;const pairs=Object.entries(copy);const lookup=new Map();pairs.forEach(([en,vars])=>{const v=vars.split('|');lookup.set(en,en);lookup.set(v[0],en);lookup.set(v[1],en)});const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:n=>n.parentElement&&!n.parentElement.closest('script,style,svg,textarea,pre,code')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{const trimmed=n.nodeValue.trim(),english=lookup.get(trimmed);if(english){const next=variant<0?english:copy[english].split('|')[variant];n.nodeValue=n.nodeValue.replace(trimmed,next)}});document.querySelectorAll('[placeholder],[title],[aria-label]').forEach(el=>['placeholder','title','aria-label'].forEach(attr=>{const raw=el.getAttribute(attr);const english=lookup.get(raw);if(english)el.setAttribute(attr,variant<0?english:copy[english].split('|')[variant])}))}
  function icon(path){return `<span class="i-wrap" style="width:18px;height:18px"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${path}</svg></span>`}
  function openCalendar(){if(typeof window.openCalendar==='function')window.openCalendar();else document.querySelector('[onclick*="openCalendar"]')?.click()}
  function init(){
    document.title='Nura App V4';
    const originalSetLanguage=window.nuraSetLanguage;
    window.nuraSetLanguage=(lang)=>{originalSetLanguage?.(lang);translateAll(lang)};
    const sidebar=document.getElementById('main-sidebar'), nav=sidebar?.querySelector('.sidebar-nav'), profile=document.querySelector('.user-menu-container');
    if(!sidebar||!nav)return;
    if(profile&&!document.querySelector('.sidebar-profile')){const slot=document.createElement('div');slot.className='sidebar-profile';slot.appendChild(profile);sidebar.insertBefore(slot,nav)}
    const bottom=document.createElement('div');bottom.className='sidebar-bottom';
    const stats=document.createElement('button');stats.className='sidebar-btn';stats.id='v4-stats-toggle';stats.title='Focus and stress';stats.innerHTML=icon('<path d="M4 16l5-5 3 3 7-8"/><path d="M14 6h5v5"/>')+'<span class="sidebar-btn-label">Stats</span><span class="v4-chevron">⌄</span>';
    const flyout=document.createElement('div');flyout.className='sidebar-flyout';flyout.id='v4-stats-menu';flyout.innerHTML='<button data-stat="focus" aria-pressed="true">✓ Focus <strong id="v4-focus-value"></strong></button><button data-stat="stress" aria-pressed="true">✓ Stress <strong id="v4-stress-value"></strong></button>';
    stats.onclick=(e)=>{e.stopPropagation();stats.classList.toggle('open');flyout.classList.toggle('open')};
    flyout.onclick=e=>{const btn=e.target.closest('[data-stat]');const type=btn?.dataset.stat;if(!type)return;const card=document.getElementById(type==='focus'?'dash-focus':'dash-stress')?.closest('.vital-big');if(!card)return;const visible=card.style.display!=='none';card.style.display=visible?'none':'';btn.setAttribute('aria-pressed',String(!visible));btn.firstChild.nodeValue=(visible?'':'✓ ')+(type==='focus'?'Focus ':'Stress ');localStorage.setItem('nura-v4-'+type,visible?'hidden':'shown')};
    const calendar=document.createElement('button');calendar.className='sidebar-btn';calendar.title='Calendar';calendar.innerHTML=icon('<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>')+'<span class="sidebar-btn-label">Calendar</span>';calendar.onclick=openCalendar;
    const language=document.createElement('button');language.className='sidebar-btn sidebar-language-btn';language.title='Language';language.innerHTML=icon('<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3a14 14 0 0 1 0 18M12 3a14 14 0 0 0 0 18"/>')+'<span class="sidebar-btn-label">Language</span>';language.onclick=()=>{const current=localStorage.getItem('nura-language')||'da';const next=current==='da'?'de':current==='de'?'en':'da';window.nuraSetLanguage?.(next);refreshLanguage()};
    const settings=sidebar.querySelector('.sidebar-settings-btn');nav.insertBefore(stats,nav.children[1]);bottom.append(calendar,language);if(settings)bottom.append(settings);sidebar.append(bottom,flyout);
    document.addEventListener('click',()=>{stats.classList.remove('open');flyout.classList.remove('open')});
    ['focus','stress'].forEach(type=>{if(localStorage.getItem('nura-v4-'+type)==='hidden'){const btn=flyout.querySelector(`[data-stat="${type}"]`);btn?.click()}});makeColourPicker(); smoothVideo(); window.nuraSetLanguage(localStorage.getItem('nura-language')||'da'); refreshLanguage();
  }
  function refreshLanguage(){const l=localStorage.getItem('nura-language')||'da', t=labels[l]||labels.en;document.querySelector('#v4-stats-menu [data-stat="focus"]').childNodes[0].nodeValue=t.focus+' ';document.querySelector('#v4-stats-menu [data-stat="stress"]').childNodes[0].nodeValue=t.stress+' ';document.querySelector('#v4-stats-toggle .sidebar-btn-label').textContent='Stats';document.querySelectorAll('.sidebar-btn').forEach(b=>{if(b.title==='Calendar')b.querySelector('.sidebar-btn-label').textContent=t.calendar;if(b.title==='Language')b.querySelector('.sidebar-btn-label').textContent=t.language;if(b.title==='Settings')b.querySelector('.sidebar-btn-label').textContent=t.settings});document.getElementById('v4-focus-value').textContent=document.getElementById('top-focus')?.textContent||'--';document.getElementById('v4-stress-value').textContent=document.getElementById('top-stress')?.textContent||'--'}
  function makeColourPicker(){const control=document.querySelector('.colour-popup-controls');if(!control||document.getElementById('v4-colour-picker'))return;const picker=document.createElement('input');picker.id='v4-colour-picker';picker.className='v4-colour-picker';picker.type='color';picker.value=document.getElementById('colour-popup-hex')?.value||'#7c5cfc';picker.setAttribute('aria-label','Choose accent colour');picker.oninput=()=>{document.getElementById('colour-popup-hex').value=picker.value;window.applyCustomColour?.(picker.value)};control.prepend(picker)}
  function smoothVideo(){const video=document.getElementById('nura-desert-video');if(!video)return;video.preload='metadata';video.playbackRate=1;video.addEventListener('canplay',()=>video.classList.add('ready'),{once:true});if(video.readyState<3){video.pause();video.addEventListener('canplaythrough',()=>video.play().catch(()=>{}),{once:true})}}
  document.addEventListener('DOMContentLoaded',init);
})();
