/* Nura V5: simplify the shell and add account-aware NuraQuiz. */
(()=>{
  const guest=()=>{try{const p=JSON.parse(localStorage.getItem('nura-user-profile')||'{}');return !!(p.isGuest||!p.email)}catch{return true}};
  const modal=()=>{let el=document.querySelector('.nura-guest-message');if(!el){el=document.createElement('div');el.className='nura-guest-message';el.innerHTML='<div class="nura-guest-card"><h2>Login required</h2><p>Login to use settings, Nura Mind, NuraQuiz, and NeuroMind plans. Guest mode only includes casual Nura Chat.</p><button class="btn primary" id="nura-guest-login">Log in</button></div>';document.body.append(el);el.querySelector('#nura-guest-login').onclick=()=>{el.classList.remove('show');window.authShowSignIn?.();window.showSignOutGate?.()};el.onclick=e=>{if(e.target===el)el.classList.remove('show')}}el.classList.add('show')};
  function initials(){const b=document.querySelector('.sidebar-profile .user-badge');const img=document.getElementById('user-badge-img');if(!b||!img)return;const p=JSON.parse(localStorage.getItem('nura-user-profile')||'{}');const letter=(p.name||'G').trim().charAt(0).toUpperCase();if(!img.getAttribute('src')){img.style.display='none';let a=b.querySelector('.v5-avatar');if(!a){a=document.createElement('span');a.className='v5-avatar';a.style.cssText='width:32px;height:32px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,var(--accent),#d6b5ff);color:#fff;font:700 15px Outfit,sans-serif';b.append(a)}a.textContent=letter}}
  function quizMode(){const tutor=document.getElementById('tutor'), top=tutor?.querySelector('.tutor-topbar'), main=tutor?.querySelector('.tutor-main'), quiz=document.getElementById('quiz-panel');if(!tutor||!top||!main||!quiz)return;const holder=document.createElement('div');holder.className='nuraquiz-pane';holder.append(quiz);main.append(holder);const switcher=document.createElement('div');switcher.className='nura-mode-switcher';switcher.innerHTML='<button class="active" data-mode="chat">Nura Chat</button><button data-mode="quiz">NuraQuiz</button>';top.insertBefore(switcher,top.querySelector('.mode-tag'));switcher.onclick=e=>{const mode=e.target.dataset.mode;if(!mode)return;if(mode==='quiz'&&guest()){modal();return}switcher.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));holder.classList.toggle('active',mode==='quiz');tutor.querySelector('.tutor-chat-area').style.display=mode==='quiz'?'none':'';tutor.querySelector('.tutor-input-area').style.display=mode==='quiz'?'none':'';tutor.querySelector('.file-side-panel').style.display=mode==='quiz'?'none':''};}
  function quizResults(){const old=window.showQuizResults;window.showQuizResults=function(){old?.();const score=(document.getElementById('quiz-final-score')?.textContent||'0 / 1').match(/(\d+)\s*\/\s*(\d+)/);const pct=score?Math.round((Number(score[1])/Math.max(Number(score[2]),1))*100):0;const history=JSON.parse(localStorage.getItem('nura-quiz-history')||'[]');const prior=history.length?history[history.length-1].pct:null;history.push({pct,at:new Date().toISOString()});localStorage.setItem('nura-quiz-history',JSON.stringify(history.slice(-50)));let pop=document.querySelector('.nura-quiz-result');if(!pop){pop=document.createElement('div');pop.className='nura-quiz-result';pop.innerHTML='<div class="nura-quiz-result-card"><h2>NuraQuiz result</h2><div class="nura-quiz-result-score"></div><p></p><button class="btn primary">Done</button></div>';document.body.append(pop);pop.querySelector('button').onclick=()=>pop.classList.remove('show')}pop.querySelector('.nura-quiz-result-score').textContent=pct+'%';pop.querySelector('p').textContent=prior===null?'Your first saved quiz result.':`${pct-prior>=0?'+':''}${pct-prior}% from your previous quiz.`;pop.classList.add('show')};}
  function restrictions(){const mind=window.navNuraMind;window.navNuraMind=function(btn){if(guest()){modal();return}return mind?.(btn)};const settings=window.openSettingsModal;window.openSettingsModal=function(){if(guest()){modal();return}return settings?.()};}
  function languageSetting(){const ui=document.getElementById('spanel-ui');if(!ui||document.getElementById('v5-language-setting'))return;const row=document.createElement('div');row.className='s-row';row.id='v5-language-setting';row.innerHTML='<label class="s-label">Language</label><select class="s-input" style="max-width:160px"><option value="en">English</option><option value="da">Dansk</option><option value="de">Deutsch</option></select>';const select=row.querySelector('select');select.value=localStorage.getItem('nura-language')||'da';select.onchange=()=>window.nuraSetLanguage?.(select.value);ui.append(row)}
  function removeWatermark(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(n=>{if(/nura.*email.*verif|email.*verification.*required/i.test(n.nodeValue))n.parentElement.style.display='none'})}
  document.addEventListener('DOMContentLoaded',()=>{document.querySelector('#v4-stats-toggle')?.remove();document.querySelector('#v4-stats-menu')?.remove();document.querySelectorAll('.sidebar-bottom>.sidebar-language-btn,.sidebar-bottom>button[title="Calendar"]').forEach(e=>e.remove());document.querySelector('.sidebar-nav button[onclick*="quiz-panel"]')?.remove();quizMode();quizResults();restrictions();languageSetting();removeWatermark();setTimeout(initials,60)});
})();
