/* Nura V6: Firebase-config-aware AI start, in-chat mode menu, complete UI copy pass. */
(()=>{
  const translations={
    'What do you want to learn today?':'Hvad vil du lære i dag?|Was möchtest du heute lernen?',
    'Open the Files panel or paste text to give Nura context — then ask anything.':'Åbn Filer-panelet eller indsæt tekst for at give Nura kontekst — spørg derefter om hvad som helst.|Öffne Dateien oder füge Text ein, um Nura Kontext zu geben — frage dann alles.',
    'No files loaded':'Ingen filer indlæst|Keine Dateien geladen','New Chat':'Ny chat|Neuer Chat','Files':'Filer|Dateien','Send':'Send|Senden','Add Note':'Tilføj note|Notiz hinzufügen','Study Notes Log':'Studienotater|Lernnotizen','Auto-saved from Nura Mind · Click to open editor':'Gemmes automatisk fra Nura Mind · Klik for at åbne editoren|Automatisch von Nura Mind gespeichert · Zum Öffnen klicken','Add subject...':'Tilføj fag...|Fach hinzufügen','No notes yet.':'Ingen noter endnu.|Noch keine Notizen.','Chat with Nura Mind and ask it to save to notes.':'Chat med Nura Mind og bed den gemme noter.|Chatte mit Nura Mind und bitte es, Notizen zu speichern.','Nura Chat':'Nura Chat|Nura Chat','NuraQuiz':'NuraQuiz|NuraQuiz','Settings':'Indstillinger|Einstellungen','Home':'Hjem|Startseite','Watch':'Ur|Uhr','Notes':'Noter|Notizen','Language':'Sprog|Sprache','Theme':'Tema|Design','Light':'Lys|Hell','Dark':'Mørk|Dunkel','Custom colour':'Brugerdefineret farve|Benutzerdefinierte Farbe','Choose your accent colour':'Vælg din accentfarve|Akzentfarbe wählen','Generate Quiz':'Start quiz|Quiz starten','TOPIC / SUBJECT':'EMNE / FAG|THEMA / FACH','QUESTIONS (max 20)':'SPØRGSMÅL (maks. 20)|FRAGEN (max. 20)','Try Another Quiz':'Prøv en ny quiz|Neues Quiz versuchen','Question':'Spørgsmål|Frage','Score':'Resultat|Punktzahl'
  };
  function applyCopy(lang){const n=lang==='da'?0:lang==='de'?1:-1;const reverse=new Map;Object.entries(translations).forEach(([en,value])=>{reverse.set(en,en);value.split('|').forEach(v=>reverse.set(v,en))});const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:x=>x.parentElement&&!x.parentElement.closest('script,style,svg,textarea,pre,code')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT});const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);nodes.forEach(x=>{const t=x.nodeValue.trim(),en=reverse.get(t);if(en)x.nodeValue=x.nodeValue.replace(t,n<0?en:translations[en].split('|')[n])});document.querySelectorAll('[placeholder],[title],[aria-label]').forEach(el=>['placeholder','title','aria-label'].forEach(a=>{const en=reverse.get(el.getAttribute(a));if(en)el.setAttribute(a,n<0?en:translations[en].split('|')[n])}))}
  function profileTopRight(){const profile=document.querySelector('.user-menu-container');if(!profile)return;let anchor=document.getElementById('v6-profile-anchor');if(!anchor){anchor=document.createElement('div');anchor.id='v6-profile-anchor';document.body.append(anchor)}anchor.append(profile)}
  function modeMenu(){const switcher=document.querySelector('.nura-mode-switcher');if(!switcher||document.getElementById('v6-mode-menu'))return;const select=document.createElement('select');select.id='v6-mode-menu';select.setAttribute('aria-label','Choose Nura AI mode');select.innerHTML='<option value="chat">Nura Chat</option><option value="quiz">NuraQuiz</option>';select.onchange=()=>switcher.querySelector(`[data-mode="${select.value}"]`)?.click();switcher.querySelectorAll('button').forEach(b=>b.style.display='none');switcher.append(select)}
  function waitForFirebaseKey(){['sendMsg','generateQuiz'].forEach(name=>{const original=window[name];if(typeof original!=='function'||original._v6)return;window[name]=async function(...args){if(!window.getApiKey?.()&&typeof window._fetchConfigKey==='function'){await window._fetchConfigKey();await new Promise(r=>setTimeout(r,80))}return original.apply(this,args)};window[name]._v6=true})}
  document.addEventListener('DOMContentLoaded',()=>{profileTopRight();modeMenu();waitForFirebaseKey();const set=window.nuraSetLanguage;window.nuraSetLanguage=(lang)=>{set?.(lang);applyCopy(lang)};applyCopy(localStorage.getItem('nura-language')||'da');document.querySelectorAll('*').forEach(el=>{if(/nura\s*·\s*email verification required/i.test(el.textContent||''))el.style.display='none'})});
})();
